### PR TITLE
feat: improving the look and feel of columns by adding more padding

### PR DESCRIPTION
**Pull request by klcodanr**
Adds more padding so columns line up correctly.

Test URLs:
- Before: https://main--aem-assets-highlights--adobe.hlx.page/block-playground
- After: https://improve-columns-ui--aem-assets-highlights--adobe.hlx.page/block-playground

### CODE REVIEW

**Review by tmathern — CHANGES_REQUESTED** [review]
Can you use a link showcasing the change? For now I pointed to the June newsletter, but feel free to create a draft folder and create files to showcase your changes there.

**Review by tmathern — COMMENTED** [review]
```
/home/runner/work/aem-assets-highlights/aem-assets-highlights/blocks/columns/columns.js
Error:   12:109  error  Do not nest ternary expressions  no-nested-ternary
```

Can you fix that too?

**Review by tmathern — CHANGES_REQUESTED** [review]
Please review the styles to introduce a variable for fonts and reuse the variable instead.

**Comment by klcodanr** [comment]
Confused, this change doesn't include font CSS nor does it introduce the console.log statements.

**Pull request merged**
